### ISSUE TITLE
Get memes from a particular subreddit

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#42]
Currently the !obmeme command gets a random meme from a random subreddit in the choices folder. If the user passes an argument, it should override the choices to get memes from the arguments passed subreddit.
So you will have to check if there are no arguments, in that case, use the choices folder, if there are arguments, make a new array of all arguments(names of subreddit) and pass the temporarily created array to the fillMemes.
Make sure to put the code in a try-catch so that if the subreddit name is wrong, it should reply with "Wrong subreddit name"

**Comment by markvrma** [comment]
I would like to work on this

**Comment by hitenSharm** [comment]
@markvrma I will bump the difficulty level to hard if you are willing to do something similar for the !obgif command. You will have to work with the TENOR API for that and also write appropriate messages as currently there is no implementation done if the gif doesn't exist(as I said, similar to the meme command i.e. a try-catch)

**Comment by markvrma** [comment]
I'll do it. However try-catch is not working on !obmeme since the meme API makes multiple requests and then falls into `handleError()` in `index.js` file. I'm planning to try and limit the number of requests the API makes but it could backfire if the API ever becomes slow. Is there a better way to do this?

**Comment by hitenSharm** [comment]
Are you doing a try-catch in the fetching memes file or the main command execution? I think a try-catch in the fillMemes.js should work in checking if the meme can be fetched.

**Comment by markvrma** [comment]
It's from `fillMemes.js` I think this could be due to implementing `try-catch` in async-await or the API request timeout not being caught initially. I tried `try-catch` as well as `.catch`. I have now modified `handleError.js` It's working now.
```java
case "TypeError":
      if (command === "obmeme") {
        return "wrong subreddit";
        break;
      } else {
        return "Queue is non-existent";
        break;
      }
```  
![fixedsubreddit](https://user-images.githubusercontent.com/78155861/138653126-713cbf00-66d7-4a86-8500-f4365b5030f2.png)

we can make better ErrorHandling messages for other scenarios and avoid try-catch.
